inventory/urls.py
from django.urls import path
from inventory import views as inventory_views

urlpatterns = [
    path('stations/<int:station_pk>/orders', inventory_views.station_orders_dashboard,
         name='station orders dashboard'),

    path('orders/<int:order_pk>', inventory_views.make_station_order,
         name='make station order'),

    path('orders/<int:order_pk>/fleet/<str:vehicle_path>', inventory_views.make_vehicle_order,
         name='make vehicle order'),

    path('orders/<int:order_pk>/confirmation', inventory_views.station_order_confirmation,
         name='station order confirmation'),

    path('orders/<int:order_pk>/summary', inventory_views.station_order_summary,
         name='station order summary'),
]

jcc/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('fleet.urls')),
    path('inventory/', include('inventory.urls'))
]

inventory/models.py
from django.db import models
from django.apps import apps


class Bag(models.Model):
    # Collection of compartments/pockets/pouches, see class Compartments for content.
    # May also hold loose items (optional) for single space bags (no compartmentalization).
    name = models.CharField(max_length=40)
    brand = models.CharField(max_length=40,
                             blank=True,
                             null=True)
    ordering = models.PositiveSmallIntegerField(blank=True,
                                                null=True)

    def __str__(self):
        return self.name


class BagCompartment(models.Model):
    # Section of the bag that holds items and other kits.
    # For example "Main Top Compartment", "Top Outside Pouch", etc.
    name = models.CharField(max_length=40)
    ordering = models.PositiveSmallIntegerField(blank=True,
                                                null=True)
    bag = models.ForeignKey(Bag,
                            blank=True,
                            null=True,
                            on_delete=models.CASCADE)

    def get_bag_name(self):
        try:
            bag_name = self.bag.name
            return bag_name
        except AttributeError:
            return "Not Yet Assigned To Any Bags"

    def __str__(self):
        return '{} _in_ {}'.format(self.name, self.get_bag_name())

    class Meta:
        ordering = ['ordering']


class BagCompartmentToItemAssociation(models.Model):
    # Defines quantity of the item in the bag compartment.
    # Example: 'Bio-Hazard Bag, Large' x2 in 'Center Pocket'.
    bag_compartment = models.ForeignKey(BagCompartment,
                                        blank=True,
                                        null=True,
                                        on_delete=models.CASCADE)
    item = models.ForeignKey('Item',
                             blank=True,
                             null=True,
                             on_delete=models.CASCADE)
    quantity = models.SmallIntegerField()
    ordering = models.PositiveSmallIntegerField(blank=True,
                                                null=True)

    def __str__(self):
        item_details = self.item.name

        if self.item.size:
            item_details = '{}, {}'.format(item_details, self.item.size)
        item_details = '{} (x{})' .format(item_details, self.quantity)

        return '{} in {}'.format(item_details, self.bag_compartment.name)

    class Meta:
        verbose_name = "Bag Compartment to Item Association"


class Kit(models.Model):
    # Collection of items combined in a single case/box/carrier to tackle particular function
    # For example "Glucometer Kit", "Airway Kit", "Suction Unit", "IV Kit", "AirTraq", etc.
    name = models.CharField(max_length=40)
    brand = models.CharField(max_length=40,
                             blank=True,
                             null=True)
    ordering = models.PositiveSmallIntegerField(blank=True,
                                                null=True)
    bag_compartment = models.ForeignKey(BagCompartment,
                                        blank=True,
                                        null=True,
                                        on_delete=models.CASCADE)

    def get_bag_compartment_name(self):
        try:
            bag_compartment_name = self.bag_compartment.name
            return bag_compartment_name
        except AttributeError:
            return "Not Yet Assigned to Any Bag Compartments"

    def get_bag_name(self):
        try:
            bag_compartment = self.bag_compartment
            bag_name = bag_compartment.get_bag_name()
            return bag_name
        except AttributeError:
            # Exception also being caught in BagCompartment.get_bag_name()
            return "Not Yet Assigned To Any Bags"

    def __str__(self):
        return '{} _in_ {} >> {}'.format(self.name, self.get_bag_name(), self.get_bag_compartment_name())


class KitToItemAssociation(models.Model):
    # Defines quantity of the item in the kit.
    # Example: 'Protective Lancet' x10 in 'Glucometer Kit'.
    kit = models.ForeignKey(Kit,
                            blank=True,
                            null=True,
                            on_delete=models.CASCADE)
    item = models.ForeignKey('Item',
                             blank=True,
                             null=True,
                             on_delete=models.CASCADE)
    quantity = models.SmallIntegerField()
    ordering = models.PositiveSmallIntegerField(blank=True,
                                                null=True)

    def __str__(self):
        item_details = self.item.name

        if self.item.size:
            item_details = '{}, {}'.format(item_details, self.item.size)
        item_details = '{} (x{})' .format(item_details, self.quantity)

        return '{} in {}'.format(item_details, self.kit.name)

    class Meta:
        verbose_name = "Kit to Item Association"


class KitCompartment(models.Model):
    # Section of the kit that holds items.
    # For example "Pocket Under Blades", "Pocket Under Syringes", etc.
    name = models.CharField(max_length=40)
    ordering = models.PositiveSmallIntegerField(blank=True,
                                                null=True)
    kit = models.ForeignKey(Kit,
                            blank=True,
                            null=True,
                            on_delete=models.CASCADE)

    def get_kit_name(self):
        try:
            return self.kit.name
        except AttributeError:
            return "Not Yet Assigned to Any Kits"

    def __str__(self):
        return '{} _in_ {}'.format(self.name, self.get_kit_name())


class KitCompartmentToItemAssociation(models.Model):
    # Defines quantity of the item in the kit compartment.
    # Example: 'Lubricant, Single Use' x4 in 'ETT Side'.
    kit_compartment = models.ForeignKey(KitCompartment,
                                        blank=True,
                                        null=True,
                                        on_delete=models.CASCADE)
    item = models.ForeignKey('Item',
                             blank=True,
                             null=True,
                             on_delete=models.CASCADE)
    quantity = models.SmallIntegerField()
    ordering = models.PositiveSmallIntegerField(blank=True,
                                                null=True)

    def __str__(self):
        item_details = self.item.name

        if self.item.size:
            item_details = '{}, {}'.format(item_details, self.item.size)
        item_details = '{} (x{})' .format(item_details, self.quantity)

        return '{} in {}'.format(item_details, self.kit_compartment.name)

    class Meta:
        verbose_name = "Kit Compartment to Item Association"


class Item(models.Model):
    # Single resource
    # For example "Band Aid", "Syringe", etc.
    name = models.CharField(max_length=40)
    size = models.CharField(max_length=40,
                            blank=True)
    brand = models.CharField(max_length=40,
                             blank=True,
                             null=True)
    ordering = models.PositiveSmallIntegerField(blank=True,
                                                null=True)
    notes = models.CharField(max_length=60,
                             blank=True)
    HOSPITAL = 'HOSPITAL'
    EMS_COMS = 'EMS_COMS'
    SUPPLIED_BY_CHOICES = [
        (HOSPITAL, 'Hospital'),
        (EMS_COMS, 'EMS Coms'),
    ]
    supplied_by = models.CharField(max_length=10,
                                   choices=SUPPLIED_BY_CHOICES,
                                   default=HOSPITAL)

    def __str__(self):
        item_details = self.name

        if self.brand:
            item_details = '{} by {}'.format(item_details, self.brand)
        if self.size:
            item_details = '{}, {}'.format(item_details, self.size)
        if self.notes:
            item_details = '{} ({})'.format(item_details, self.notes)

        return item_details

    class Meta:
        ordering = ['name', 'size']


class VehicleOrder(models.Model):
    vehicle = models.ForeignKey('fleet.Vehicle',
                                blank=True,
                                null=True,
                                on_delete=models.CASCADE)
    station_order = models.ForeignKey('StationOrder',
                                      blank=True,
                                      null=True,
                                      on_delete=models.CASCADE)

    def __str__(self):
        return self.vehicle.name


class VehicleOrderToItemAssociation(models.Model):
    # Defines quantity of the item in the bag order.
    vehicle_order = models.ForeignKey(VehicleOrder,
                                      blank=True,
                                      null=True,
                                      on_delete=models.CASCADE)
    bag = models.ForeignKey(Bag,
                            blank=True,
                            null=True,
                            on_delete=models.CASCADE)
    item = models.ForeignKey(Item,
                             on_delete=models.CASCADE)
    quantity = models.SmallIntegerField()

    def __str__(self):
        return self.item.name

    class Meta:
        verbose_name = "Vehicle Order To Item Association"


class StationOrder(models.Model):
    # Summarizes the order for the station on inventory day.
    station = models.ForeignKey('fleet.Station',
                                blank=True,
                                null=True,
                                on_delete=models.CASCADE)
    is_submitted = models.BooleanField(default=False)
    timestamp = models.DateTimeField(auto_now_add=True)

    def get_vehicle_order_to_item_associations(self):
        vehicle_orders = self.vehicleorder_set.all()
        vehicle_order_to_item_associations = [
            vehicle_order_to_item_association

inventory/forms.py
from django import forms

templates/inventory/email_body.html
<p>
{% for item, quantity in items_ordered.items %}
  <br>{{ item }} x{{ quantity }}
{% endfor %}
</p>

<p>Submitted: {{ order_timestamp.date|date:"l, M d, Y" }} at {{ order_timestamp.time|date:"Hi" }}.</p>

templates/inventory/make_station_order.html
{% extends "base.html" %}

{% block title %}{{ station_name }}{% endblock %}

{% block nav-component %}
  {% include "nav-component.html" %}
{% endblock %}

{% block content %}

  <div class="container">
    <div class="row">

      <div class="col-md-8">
        <div class="row">

          {% for vehicle in station_fleet %}
            <div class="col-md-4 col-sm-6">
              <a href="{% url 'make vehicle order' order_pk=order_pk vehicle_path=vehicle.get_path %}">

                <div class="card mb-4">
                  <div class="card-header text-center">
                    {{ vehicle.name }}
                  </div>

                  <div class="card-body">
                    <p class="card-text text-muted small">{{ station_path }}</p>
                  </div>
                </div>

              </a>
            </div>
          {% endfor %}

        </div> {# /row #}
      </div> {# /div with vehiles #}

      <div class="col-md-4">
        <div class="row">

          <div class="card mb-4">
            <div class="card-header text-center">
              Order #{{ order_pk }}
            </div> {# card-header #}

            <div class="card-body">
              {% if items_of_station_order_grouped_by_vehicle_then_bag %}
                {% for vehicle, bag_dict in items_of_station_order_grouped_by_vehicle_then_bag.items %}
                  <p class="card-text text-center mb-0">{{ vehicle }}</p>
                  {% for bag, item_dict in bag_dict.items %}
                    <p class="card-text text-center text-muted">{{ bag }}</p>
                    {% for item, quantity in item_dict.items %}
                      <p class="card-text mb-1">{{ item }} x{{ quantity }}</p>
                    {% endfor %}
                  {% endfor %}
                {% endfor %}
              {% else %}
                <p class="card-text">No EMS supplies in this order yet.</p>
              {% endif %}
            </div> {# card-body #}

            <div class="card-footer text-center">
              <a href="{% url "station order confirmation" order_pk=order_pk %}"
                 class="btn btn-outline-dark"
                 role="button">Review and Submit
              </a>
            </div> {# /card-footer #}
          </div> {# /card #}

        </div> {# /row #}
      </div> {# /div.col with StationOrder #}

    </div> {# /row #}
  </div> {# /container #}
{% endblock %}

templates/inventory/make_vehicle_order.html
{% extends "base.html" %}

{% load static %}
{% block extra_stylesheets %}
  <link rel="stylesheet"
        href="{% static "inventory/css/make_order.css" %}">
{% endblock %}

{% block title %}{{ vehicle_name }}{% endblock %}

{% block nav-component %}
  {% include "nav-component.html" %}
{% endblock %}

{% block content %}

  <form method="post">
    {% csrf_token %}
    <div class="accordion" id="bags_accordion">

      {% for vehicle_bag in vehicle_bags %}
        <div class="card">

          <div class="card-header" id="heading{{ vehicle_bag.pk }}">
            <h2 class="mb-0">
              <button class="btn btn-link collapsed" type="button" data-toggle="collapse"
                      data-target="#collapse{{ vehicle_bag.pk }}" aria-expanded="true"
                      aria-controls="collapse{{ vehicle_bag.pk }}">
                {{ vehicle_bag.name }}
              </button>
            </h2>
          </div>

          <div id="collapse{{ vehicle_bag.pk }}" class="collapse" aria-labelledby="heading{{ vehicle_bag.pk }}"
               data-parent="#bags_accordion">
            <div class="card-body">
              <div class="row">
                <div class="col-lg-3 col-md-6">

                  {% for bag_compartment in vehicle_bag.bagcompartment_set.all %}
                    <div class="text-center mb-1" style="background-color:lightgrey;">
                      {{ bag_compartment.name }}
                    </div>

                    {% for bag_compartment_to_item_association in bag_compartment.bagcompartmenttoitemassociation_set.all %}
                      <div class="form-group mb-2">
                        <input type="text" class="order-form-input" size="1"
                               id="input{{ bag_compartment_to_item_association.item.pk }}" placeholder=""
                               name="bagcompartmenttoitemassociation_{{ bag_compartment_to_item_association.pk }}">

                        {# TODO use extend for them item block below x3 #}
                        <label for="input{{ bag_compartment_to_item_association.item.pk }}"
                               class="order-form-label">
                          {{ bag_compartment_to_item_association.quantity }}x
                          {{ bag_compartment_to_item_association.item.name }}

                          {% if bag_compartment_to_item_association.item.size %},
                            {{ bag_compartment_to_item_association.item.size }}
                          {% endif %}
                          {% if bag_compartment_to_item_association.item.notes %}
                            ({{ bag_compartment_to_item_association.item.notes }})
                          {% endif %}
                          {% if bag_compartment_to_item_association.item.brand %}by
                            {{ bag_compartment_to_item_association.item.brand }}
                          {% endif %}
                        </label>
                      </div>
                    {% endfor %}

                    {% for kit in bag_compartment.kit_set.all %}
                      <div class="row pt-1">
                        <div class="col-12 text-center">
                          {{ kit.name }}
                        </div>
                      </div>

                      {% for kit_to_item_association in kit.kittoitemassociation_set.all %}
                        <div class="form-group mb-2">
                          <input type="text" class="order-form-input" size="1"
                                 id="input{{ kit_to_item_association.item.pk }}" placeholder=""
                                 name="kittoitemassociation_{{ kit_to_item_association.pk }}">

                          <label for="input{{ kit_to_item_association.item.pk }}"
                                 class="order-form-label">
                            {{ kit_to_item_association.quantity }}x
                            {{ kit_to_item_association.item.name }}

                            {% if kit_to_item_association.item.size %},
                              {{ kit_to_item_association.item.size }}
                            {% endif %}
                            {% if kit_to_item_association.item.notes %}
                              ({{ kit_to_item_association.item.notes }})
                            {% endif %}
                            {% if kit_to_item_association.item.brand %}by
                              {{ kit_to_item_association.item.brand }}
                            {% endif %}
                          </label>
                        </div>
                      {% endfor %}

                      {% for kit_compartment in kit.kitcompartment_set.all %}
                        <div class="row pt-3 mb-1">
                          <div class="col-12 mt-n3 text-center text-secondary">
                            {{ kit_compartment.name }}
                          </div>
                        </div>

                        {% for kit_compartment_to_item_association in kit_compartment.kitcompartmenttoitemassociation_set.all %}
                          <div class="form-group mb-2">
                            <input type="text" class="order-form-input" size="1"
                                   id="input{{ kit_compartment_to_item_association.item.pk }}" placeholder=""
                                   name="kitcompartmenttoitemassociation_{{ kit_compartment_to_item_association.pk }}">

                            <label for="input{{ kit_compartment_to_item_association.item.pk }}"
                                   class="order-form-label">
                              {{ kit_compartment_to_item_association.quantity }}x
                              {{ kit_compartment_to_item_association.item.name }}

                              {% if kit_compartment_to_item_association.item.size %},
                                {{ kit_compartment_to_item_association.item.size }}
                              {% endif %}
                              {% if kit_compartment_to_item_association.item.notes %}
                                ({{ kit_compartment_to_item_association.item.notes }})
                              {% endif %}
                              {% if kit_compartment_to_item_association.item.brand %}by
                                {{ kit_compartment_to_item_association.item.brand }}
                              {% endif %}
                            </label>
                          </div>
                        {% endfor %}

                        {% if kit_compartment.name in new_column_cutoffs %}
                          </div>
                          <div class="col-lg-3 col-md-6">
                        {% endif %}

                      {% endfor %}  <!-- /kit>kit_compartment -->
                    {% endfor %}  <!-- /kit -->

                  {% if bag_compartment.name in new_column_cutoffs %}
                    </div>
                    <div class="col-lg-3 col-md-6">
                  {% endif %}

                  {% endfor %} <!-- /bag_compartment -->
                  </div>  {# /col #}
              </div>  {# /row #}
            </div>  {# card-body #}
          </div>  {# collapse #}

        </div> {# /card #}

      {% endfor %}  {# /vehicle_bag in vehicle_bags #}

    </div> {# /accordion #}

    <div class="row mt-2 justify-content-center">
      <div class="col-md-2">
        <button type="submit" class="btn btn-primary btn-block">Order</button>
      </div>
    </div>

  </form>
{% endblock %}

templates/inventory/nav-component.html
<nav aria-label="breadcrumb">

  <ol class="breadcrumb">
    {% for breadcrumb in breadcrumbs %}
      {% if forloop.last %}
        <li class="breadcrumb-item my-auto active" aria-current="page">{{ breadcrumb.text }}</li>
      {% else %}
        <li class="breadcrumb-item my-auto"><a href={{ breadcrumb.link }}>{{ breadcrumb.text }}</a></li>
      {% endif %}
    {% endfor %}
    <li class="ml-auto my-auto small">
      welcome, <span id="signed_in_user">{{ user }}</span>
    </li>
    <a href="{% url "user sign out" %}"
       class="btn btn-outline-primary btn-sm ml-2"
       role="button">sign out
    </a>
  </ol>

</nav>

templates/inventory/order-form.html
<!doctype html>
<html lang="en" xmlns="http://www.w3.org/1999/html">
<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

  <title>{{ vehicle_name }}</title>
</head>
<body style="overflow-y:scroll;">

{#<nav aria-label="breadcrumb">#}
{#  <ol class="breadcrumb">#}
{#    <li class="breadcrumb-item"><a href="{% url 'home' %}">Home</a></li>#}
{#    <li class="breadcrumb-item"><a href="{% url 'station #' station_id %}">{{ station_name }}</a></li>#}
{#    <li class="breadcrumb-item active" aria-current="page">{{ vehicle_name }}</li>#}
{#  </ol>#}
{#</nav>#}

<form method="post">{% csrf_token %}
  <div class="accordion" id="bags_accordion">

    {% for vehicle_bag in vehicle_bags %}
      <div class="card">

        <div class="card-header" id="heading{{ vehicle_bag.pk }}">
          <h2 class="mb-0">
            <button class="btn btn-link collapsed" type="button" data-toggle="collapse"
                    data-target="#collapse{{ vehicle_bag.pk }}" aria-expanded="true"
                    aria-controls="collapse{{ vehicle_bag.pk }}">
              {{ vehicle_bag.name }}
            </button>
          </h2>
        </div>

        <div id="collapse{{ vehicle_bag.pk }}" class="collapse" aria-labelledby="heading{{ vehicle_bag.pk }}"
             data-parent="#bags_accordion">
          <div class="card-body">
            <div class="row">
              <div class="col-md-3 col-sm-6">

                {% for bag_compartment in vehicle_bag.bagcompartment_set.all %}
                  <div class="text-center mb-1" style="background-color:lightgrey;">
                    {{ bag_compartment.name }}
                  </div>

                  {% for bag_compartment_to_item_association in bag_compartment.bagcompartmenttoitemassociation_set.all %}
                    <div class="form-group row mb-0">
                      <div class="col-sm-2">
                        <input type="text" class="form-control form-control-sm"
                               id="input{{ bag_compartment_to_item_association.item.pk }}" placeholder=""
                               name="bagcompartmenttoitemassociation_{{ bag_compartment_to_item_association.pk }}">
                      </div>

                      {# TODO use extend for them item block below x3 #}
                      <div class="col-sm-10 pl-0">
                        <label for="input{{ bag_compartment_to_item_association.item.pk }}"
                               class="col-form-label col-form-label">
                          {{ bag_compartment_to_item_association.item.pk }}pk
                          {{ bag_compartment_to_item_association.quantity }}x
                          {{ bag_compartment_to_item_association.item.name }}
                          {% if bag_compartment_to_item_association.item.size %},
                            {{ bag_compartment_to_item_association.item.size }}
                          {% endif %}
                          {% if bag_compartment_to_item_association.item.notes %}
                            ({{ bag_compartment_to_item_association.item.notes }})
                          {% endif %}
                          {% if bag_compartment_to_item_association.item.brand %}by
                            {{ bag_compartment_to_item_association.item.brand }}
                          {% endif %}
                        </label>
                      </div>
                    </div>
                  {% endfor %}

                  {% for kit in bag_compartment.kit_set.all %}
                    <div class="row pt-1">
                      <div class="col-12 text-center">
                        {{ kit.name }}
                      </div>
                    </div>

                    {% for kit_to_item_association in kit.kittoitemassociation_set.all %}
                      <div class="form-group row mb-0">
                        <div class="col-sm-2">
                          <input type="text" class="form-control form-control-sm"
                                 id="input{{ kit_to_item_association.item.pk }}" placeholder=""
                                 name="kittoitemassociation_{{ kit_to_item_association.pk }}">
                        </div>
                        <div class="col-sm-10 pl-0">
                          <label for="input{{ kit_to_item_association.item.pk }}"
                                 class="col-form-label col-form-label">
                            {{ kit_to_item_association.item.pk }}pk
                            {{ kit_to_item_association.quantity }}x {{ kit_to_item_association.item.name }}
                            {% if kit_to_item_association.item.size %},
                              {{ kit_to_item_association.item.size }}
                            {% endif %}
                            {% if kit_to_item_association.item.notes %}
                              ({{ kit_to_item_association.item.notes }})
                            {% endif %}
                            {% if kit_to_item_association.item.brand %}by
                              {{ kit_to_item_association.item.brand }}
                            {% endif %}
                          </label>
                        </div>
                      </div>
                    {% endfor %}

                    {% for kit_compartment in kit.kitcompartment_set.all %}
                      <div class="row pt-3 mb-1">
                        <div class="col-12 mt-n3 text-center text-secondary">
                          {{ kit_compartment.name }}
                        </div>
                      </div>

                      {% for kit_compartment_to_item_association in kit_compartment.kitcompartmenttoitemassociation_set.all %}
                        <div class="form-group row mb-0">
                          <div class="col-sm-2">
                            <input type="text" class="form-control form-control-sm"
                                   id="input{{ kit_compartment_to_item_association.item.pk }}" placeholder=""
                                   name="kitcompartmenttoitemassociation_{{ kit_compartment_to_item_association.pk }}">
                          </div>
                          <div class="col-sm-10 pl-0">
                            <label for="input{{ kit_compartment_to_item_association.item.pk }}"
                                   class="col-form-label col-form-label">
                              {{ kit_compartment_to_item_association.item.pk }}pk
                              {{ kit_compartment_to_item_association.quantity }}x
                              {{ kit_compartment_to_item_association.item.name }}
                              {% if kit_compartment_to_item_association.item.size %},
                                {{ kit_compartment_to_item_association.item.size }}
                              {% endif %}
                              {% if kit_compartment_to_item_association.item.notes %}
                                ({{ kit_compartment_to_item_association.item.notes }})
                              {% endif %}
                              {% if kit_compartment_to_item_association.item.brand %}by
                                {{ kit_compartment_to_item_association.item.brand }}
                              {% endif %}
                            </label>
                          </div>
                        </div>
                      {% endfor %}

                      {% if kit_compartment.name in new_column_cutoffs %}
                        </div>
                        <div class="col-md-3 col-sm-6">
                      {% endif %}

                    {% endfor %}  <!-- /kit>kit_compartment -->
                  {% endfor %}  <!-- /kit -->

                {% if bag_compartment.name in new_column_cutoffs %}
                  </div>
                  <div class="col-md-3 col-sm-6">
                {% endif %}

                {% endfor %} <!-- /bag_compartment -->
                </div>  {# /col #}
            </div>  {# /row #}
          </div>  {# card-body #}
        </div>  {# collapse #}

      </div> {# /card #}

    {% endfor %}  {# /bag in bags #}
  </div> {# /accordion #}

  <div class="row mt-2 justify-content-center">
    <div class="col-md-2">
      <button type="submit" class="btn btn-primary btn-block">Order</button>
    </div>
  </div>

</form>

<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous">
</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous">
</script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous">
</script>
</body>
</html>